config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :places do
    resources :bookings, only: :create
    resources :place_reviews, only: :create
  end

  resources :users, only: :show do
    resources :bookings, only: :index
    get :public
    resources :user_reviews, only: :create
  end

  resources :bookings, only: [:show, :edit, :update, :destroy]
  resources :place_reviews, except: [:new, :create]
  resources :user_reviews, except: [:new, :create]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
  has_many :places, dependent: :destroy
  has_many :user_reviews, dependent: :destroy
  has_many :place_reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy

  validates :last_name, presence: true, allow_blank: false
  validates :first_name, presence: true, allow_blank: false
  validates :birth_date, presence: true, allow_blank: false

  def average
    ratings = []
    average = 0
    if user_reviews.present?
      user_reviews.each { |review| ratings << review.rating }
      average = ratings.sum.fdiv(user_reviews.count).round(1)
    else
      average = "-"
    end
    average
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @current_user = current_user
    authorize @current_user
  end

  def public
    @user = User.find(params[:user_id])
    @user_review = UserReview.new
    authorize @user
  end
end

app/views/users/public.html.erb
<!-- PUBLIC OWNER PROFILE -->

<div class="container my-5">
  <div class="row justify-content-center">

    <!-- LEFT PART -->

    <div class="col-3">

      <!-- OWNER AVATER, NUMBER OF BOOKINGS, RATING, MEMBER SINCE **** -->

      <div class="card public-card-owner">

        <div class="card-header card-owner-header">
          <div class="user-card-avatar" >
            <% if @user.photo.attached? %>
              <%= cl_image_tag @user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, height: 150, width: 150, crop: :fill%>
            <% else %>
              <%= image_tag "https://i48.servimg.com/u/f48/16/78/05/90/myster10.png", class: "avatar dropdown-toggle avatar_user_navbar", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
          </div>
        </div>

        <div class="card-body card-owner-body mx-3 border-bottom">
          <div class="bookings-and-average-rating">
            <div class="card-owner-important-info">
              <h4><i class="fas fa-calendar-check"></i><%= @user.bookings.count %></h4>
              <p>bookings</p>
            </div>
            <div class="card-owner-important-info">
              <div class="d-flex inline-flex align-items-center">
                <h4>
                  <i class="fas fa-star"></i><%= @user.average %>
                </h4>
                <h6 class="ml-1">/5</h6>
              </div>
              <p>evaluations</p>
            </div>
          </div>
          <div class="member-since-info">
            <h6>Member since <%= @user.created_at.year %></h6>
          </div>
        </div>

        <!-- OWNER REVIEW FORM -->

        <div class="card-footer card-owner-footer my-3">
          <%= simple_form_for([@user, @user_review], remote: true) do |f| %>
            <%= f.input :rating, collection: 0..5, as: :radio_buttons, input_html: { class: "radio-buttons"} %>
            <%= f.input :content, label: false, placeholder: "Write a review...", :input_html => {:rows => 5} %>
            <%= f.submit class: "btn btn-orange", value: "Send review" %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-1">
    </div>

    <!-- RIGHT PART -->

    <div class="col-7">

      <!-- HELLO MESSAGE & OWNER CITY -->
      <div class="public-owner-welcome-message">
        <h2 class="mb-3">Hey, I'm <%= @user.first_name %></h2>
        <% if @user.address.present? %>
          <h5 class="border-bottom pb-4">  <i class="fas fa-home mr-2"></i> From <%= @user.address %></h5>
        <% end %>
      </div>

      <!-- OWNER'S PLACES -->

      <% if @user.places.present? %>
        <h4 class="public-owner-listing mt-4">My places</h4>
        <div class="my-dashboard-cards my-places-cards">
          <% @user.places.each do |place| %>
            <div class="my-dashboard-card align-items-end">
              <div class="my-dashboard-card-place">
                <% if place.photos.attached? %>
                  <%= cl_image_tag place.photos.sample.key, height: 120, width: 120, crop: :fill, alt: "place-pic" %>
                <% else %>
                  <%= image_tag "monkey.jpg", height: 120, width: 120, crop: :fill, alt: "place-pic" %>
                <% end %>
                <div class="my-dashboard-card-infos">
                  <h2><%= link_to place.title, place_path(place)%></h2>
                  <h3><%= place.address.split(",")[-3] %></h3>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>

      <!-- OWNER'S REVIEWS -->

      <% if @user.user_reviews.present? %>
        <h4 class="public-owner-listing mt-4">My reviews</h4>
        <div class="my-reviews-owner-cards">
          <% @user.user_reviews.sort_by { |review| review.created_at }.reverse.each do |review| %>
            <div class="my-dashboard-card align-items-end">
              <div class="card-body d-flex">
                <div class="rating-in-card-review-public">
                  <h5 class="card-text pr-3"><i class="fas fa-star"></i> <%= review.rating %> <span style="font-size: 11px;">/5</span></h5>
                </div>
                <h5 class="card-text pl-3 border-left"><em>"<%= review.content %>"</em></h5>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row justify-content-center mt-4">
    <div class="col-10">

      <div class="my-bookings-box mb-3">
        <h3 class="my-dashboard-title">My bookings</h3>
        <div class="my-dashboard-cards">
          <% @current_user.bookings.sort_by { |booking| booking.date }.reverse.each do |booking| %>
            <div class="my-dashboard-card" id="<% if booking.date < Date.today %>card-grey<% end %>">
              <div class="my-dashboard-card-place">
                <% if booking.place.photos.attached? %>
                  <%= cl_image_tag booking.place.photos.sample.key, height: 120, width: 120, crop: :fill, alt: "place-pic" %>
                <% else %>
                  <%= image_tag "degrade-appareil.png", height: 120, width: 120, crop: :fill, alt: "place-pic" %>
                <% end %>
                <div class="my-dashboard-card-infos">
                  <h2><%= booking.date %></h2>
                  <h3><strong><%= booking.place.title %></strong>, <%= booking.place.address.split(",")[-3] %></h3>
                  <% if booking.date >= Date.today %>
                    <p id="status-orange">To come<p>
                  <% else %>
                    <p>Old<p>
                  <% end %>
                </div>
              </div>
              <div class="my-bookings-card-actions">
                <% if booking.date >= Date.today %>
                  <%= link_to 'show', place_path(booking.place), class: "btn btn-green" %>
                  <%= link_to 'edit', edit_place_path(booking.place), class: "btn btn-green" %>
                  <%= link_to 'delete', booking_path(booking), method: :delete, date: { confirm: 'Are you sure?' }, class: "btn btn-orange" %>
                <% else %>
                  <%= link_to 'show', place_path(booking.place), class: "btn btn-green" %>
                  <%= link_to 'rate the owner', user_public_path(booking.place.user), class: "btn btn-orange" %>
                  <%= link_to 'rate the place', place_path(booking.place), class: "btn btn-orange" %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>

      <div class="my-places-box mb-4">
        <h3 class="my-dashboard-title" id="green-title">My places</h3>
        <div class="my-dashboard-cards my-places-cards">
          <% @current_user.places.each do |place| %>
            <div class="my-dashboard-card align-items-end">
              <div class="my-dashboard-card-place">
                <% if place.photos.attached? %>
                  <%= cl_image_tag place.photos.sample.key, height: 120, width: 120, crop: :fill, alt: "place-pic" %>
                <% else %>
                  <%= image_tag "degrade-appareil.png", height: 120, width: 120, crop: :fill, alt: "place-pic" %>
                <% end %>
                <div class="my-dashboard-card-infos">
                  <h2><%= link_to place.title, place_path(place)%></h2>
                  <h3><%= place.address.split(",")[-3] %></h3>
                  <p id="bookings-count-green">Bookings : <%= place.bookings.count %></p>
                </div>
              </div>
              <div class="my-places-card-actions">
                <%= link_to edit_place_path(place) do %>
                  <i class="fas fa-pencil-alt"></i>
                <% end %>
                <%= link_to place_path(place), method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <i class="fas fa-trash-alt"></i>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>