config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :places do
    resources :bookings, only: :create
    resources :place_reviews, only: :create
  end

  resources :users, only: :show do
    resources :bookings, only: :index
    get :public
    resources :user_reviews, only: :create
  end

  resources :bookings, only: [:show, :edit, :update, :destroy]
  resources :place_reviews, except: [:new, :create]
  resources :user_reviews, except: [:new, :create]

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    © the spot 2020 - Tous droits réservés
  </div>
  <div class="footer-links">
    CGU |
    Politique de confidentialité |
    Cookies |
    Équipe
    <a href="#"><i class="fab fa-instagram ml-2"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="collapse navbar-collapse">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "thespot.png"%>
    <% end %>
    <%= simple_form_for :filter, url: places_path, method: :get, id: "navbar-search-form" do |f| %>
      <i class="fas fa-search"></i>
      <%= f.input :address, placeholder: "Search a city...", label: false %>
    <% end %>
  </div>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-2">
      <li class="nav-item">
        <%= link_to 'Become a host', new_place_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "All places", places_path, class: "nav-link" %>
      </li>
    </ul>
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown avatar_user_navbar">
        <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, height: 40, width: 40, crop: :fill%>
        <% else %>
          <%= image_tag "https://i48.servimg.com/u/f48/16/78/05/90/myster10.png", class: "avatar dropdown-toggle avatar_user_navbar", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "My information", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>